<?php $cidxc = array (
  6 => 
  array (
    0 => 0,
    1 => 'IT Department',
    2 => ' - IT Department',
    3 => 3,
    4 => 0,
    5 => 
    array (
      6 => 6,
    ),
  ),
  7 => 
  array (
    0 => 0,
    1 => 'Business Department',
    2 => '',
    3 => 3,
    4 => 0,
    5 => 
    array (
      7 => 7,
    ),
  ),
  8 => 
  array (
    0 => 0,
    1 => 'Design Department',
    2 => '',
    3 => 3,
    4 => 0,
    5 => 
    array (
      8 => 8,
    ),
  ),
  9 => 
  array (
    0 => 0,
    1 => 'Public',
    2 => ' - Public',
    3 => 3,
    4 => 0,
    5 => 
    array (
      9 => 9,
    ),
  ),
); ?>