<?php
/**
* copyright            : (C) 2001-2010 Advanced Internet Designs Inc.
* email                : forum@prohost.org
* $Id$
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation; version 2 of the License.
**/

/* Needed by admapprove_avatar.php, so that avatar approval/decline can be sent in the appropriate languge. */

$GLOBALS['approved_avatar_title'] = 'Your custom avatar was approved.';
$GLOBALS['approved_avatar_msg'] = 'Your avatar was approved by the administrator. It should now appear as your avatar on all your messages. If you do not see it, or see your old avatar, it is because your browser has cached the page. Try refreshing it once or twice. In most cases this will solve the caching problem.';
$GLOBALS['unapproved_avatar_title'] = 'Your custom avatar was declined.';
$GLOBALS['unapproved_avatar_msg'] = 'The administrator did not approve your avatar. The most common reasons are that your avatar was too big (size and/or dimensions) or it contains inappropriate subject matter. If you would like more information about why your avatar was rejected, contact the administrator.';
?>